name: remote ssh command
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker-Compose Remote Deployment
        uses: Qwizi/github-action-ssh-docker-compose@master
        with:
            ssh_host: ${{ secrets.HOST }}
            ssh_private_key: ${{ secrets.KEY }}
            ssh_user: ${{ secrets.USER }}
            ssh_port: ${{ secrets.PORT }}
            workspace: ${{ secrets.WORKSPACE }}
            env_args: ${{ secrets.ENV_ARGS }}
            docker_compose_filename: docker-compose.yaml
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'