name: remote ssh command
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: qwizii/cenzopapa-discord-bot:latest
      - name: Docker-Compose Remote Deployment
        uses: Qwizi/github-action-ssh-docker-compose@master
        with:
            ssh_host: ${{ secrets.HOST }}
            ssh_private_key: ${{ secrets.KEY }}
            ssh_user: ${{ secrets.USER }}
            workspace: ${{ secrets.WORKSPACE }}
            env_args: ${{ secrets.ENV_ARGS }}
            docker_compose_filename: docker-compose.prod.yaml
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'